/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @dfinity/caffeine-bindgen@0.1.0-beta.7.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Product {
    id: string;
    name: string;
    description: string;
    currency: string;
    priceInCents: bigint;
}
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface RefundRequest {
    status: RefundStatus;
    processedAt?: bigint;
    amount: bigint;
    appointmentId: string;
    requestedAt: bigint;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface DailySchedule {
    lunchBreaks: Array<string>;
    date: string;
    isOpen: boolean;
    availableStylists: bigint;
}
export interface Stylist {
    id: string;
    lunchBreakStart?: string;
    name: string;
    isAvailable: boolean;
    lunchBreakEnd?: string;
    isOnLunchBreak: boolean;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface http_header {
    value: string;
    name: string;
}
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface ShoppingItem {
    productName: string;
    currency: string;
    quantity: bigint;
    priceInCents: bigint;
    productDescription: string;
}
export interface Appointment {
    id: string;
    status: AppointmentStatus;
    depositAmount: bigint;
    assignedStylist?: string;
    paymentStatus: PaymentStatus;
    stylistRequest?: string;
    date: string;
    createdAt: bigint;
    parentPhone: string;
    updatedAt: bigint;
    childFirstName: string;
    childLastName: string;
    refundEligible: boolean;
    timeSlot: string;
}
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export interface EffectSettings {
    tone: number;
    speed: number;
    preset?: VoiceEffectPreset;
    pitch: number;
}
export type StripeSessionStatus = {
    __kind__: "completed";
    completed: {
        userPrincipal?: string;
        response: string;
    };
} | {
    __kind__: "failed";
    failed: {
        error: string;
    };
};
export interface TTSAudio {
    id: string;
    createdAt: bigint;
    text: string;
    audioBlob: ExternalBlob;
    voiceProfileId?: string;
    effectSettings: EffectSettings;
}
export interface VoiceProfile {
    id: string;
    userId: Principal;
    name: string;
    createdAt: bigint;
    audioBlob?: ExternalBlob;
    updatedAt: bigint;
    trainingStatus: TrainingStatus;
    referencePhrases: Array<string>;
}
export interface StripeConfiguration {
    allowedCountries: Array<string>;
    secretKey: string;
}
export interface UserProfile {
    name: string;
    email: string;
    phone: string;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export enum AppointmentStatus {
    cancelled = "cancelled",
    completed = "completed",
    booked = "booked",
    confirmed = "confirmed"
}
export enum PaymentStatus {
    pending = "pending",
    paid = "paid",
    refunded = "refunded",
    notRequired = "notRequired"
}
export enum RefundStatus {
    pending = "pending",
    approved = "approved",
    rejected = "rejected",
    processed = "processed"
}
export enum TrainingStatus {
    notStarted = "notStarted",
    completed = "completed",
    inProgress = "inProgress",
    failed = "failed"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum VoiceEffectPreset {
    reverb = "reverb",
    alien = "alien",
    deep = "deep",
    echo = "echo",
    robotic = "robotic",
    chipmunk = "chipmunk"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blob_hash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    addDailySchedule(schedule: DailySchedule): Promise<void>;
    addProduct(product: Product): Promise<void>;
    addStylist(stylist: Stylist): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    cancelAppointment(id: string): Promise<void>;
    createAppointment(appointment: Appointment): Promise<void>;
    createCheckoutSession(items: Array<ShoppingItem>, successUrl: string, cancelUrl: string): Promise<string>;
    createVoiceProfile(name: string, referencePhrases: Array<string>): Promise<string>;
    deleteDailySchedule(date: string): Promise<void>;
    deleteProduct(id: string): Promise<void>;
    deleteStylist(id: string): Promise<void>;
    deleteTTSAudio(audioId: string): Promise<void>;
    deleteVoiceProfile(profileId: string): Promise<void>;
    getAppointment(id: string): Promise<Appointment | null>;
    getAppointments(): Promise<Array<Appointment>>;
    getAppointmentsByDate(date: string): Promise<Array<Appointment>>;
    getAppointmentsByDateAndTimeSlot(date: string, timeSlot: string): Promise<Array<Appointment>>;
    getAppointmentsByDateRange(startDate: string, endDate: string): Promise<Array<Appointment>>;
    getAppointmentsByDateRangeAndStatus(startDate: string, endDate: string, status: AppointmentStatus): Promise<Array<Appointment>>;
    getAppointmentsByDateRangeAndTimeSlot(startDate: string, endDate: string, timeSlot: string): Promise<Array<Appointment>>;
    getAppointmentsByPhone(phone: string): Promise<Array<Appointment>>;
    getAppointmentsByPhoneAndDateRange(phone: string, startDate: string, endDate: string): Promise<Array<Appointment>>;
    getAppointmentsByStatus(status: AppointmentStatus): Promise<Array<Appointment>>;
    getAppointmentsByStatusAndDate(status: AppointmentStatus, date: string): Promise<Array<Appointment>>;
    getAppointmentsByStatusAndDateRange(status: AppointmentStatus, startDate: string, endDate: string): Promise<Array<Appointment>>;
    getAppointmentsByStatusAndTimeSlot(status: AppointmentStatus, timeSlot: string): Promise<Array<Appointment>>;
    getAppointmentsByStatusAndTimeSlotAndDateRange(status: AppointmentStatus, timeSlot: string, startDate: string, endDate: string): Promise<Array<Appointment>>;
    getAppointmentsByStylist(stylistId: string): Promise<Array<Appointment>>;
    getAppointmentsByStylistAndDateRange(stylistId: string, startDate: string, endDate: string): Promise<Array<Appointment>>;
    getAppointmentsByTimeSlot(timeSlot: string): Promise<Array<Appointment>>;
    getAvailableDays(): Promise<Array<string>>;
    getAvailableSlotsForDay(date: string): Promise<Array<string>>;
    getAvailableSlotsForStylist(stylistId: string, date: string): Promise<Array<string>>;
    getAvailableStylistsForSlot(date: string, timeSlot: string): Promise<Array<Stylist>>;
    getAvailableTimeSlots(date: string): Promise<Array<string>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getClosedDays(): Promise<Array<string>>;
    getDailySchedules(): Promise<Array<DailySchedule>>;
    getLunchBreaksForDate(date: string): Promise<Array<Stylist>>;
    getProducts(): Promise<Array<Product>>;
    getRefundRequests(): Promise<Array<RefundRequest>>;
    getStripeSessionStatus(sessionId: string): Promise<StripeSessionStatus>;
    getStylistAvailability(date: string): Promise<Array<Stylist>>;
    getStylists(): Promise<Array<Stylist>>;
    getTTSAudio(): Promise<Array<TTSAudio>>;
    getTTSAudioById(audioId: string): Promise<TTSAudio | null>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getVoiceProfile(profileId: string): Promise<VoiceProfile | null>;
    getVoiceProfiles(): Promise<Array<VoiceProfile>>;
    initializeAccessControl(): Promise<void>;
    isCallerAdmin(): Promise<boolean>;
    isStripeConfigured(): Promise<boolean>;
    processRefund(appointmentId: string, approve: boolean): Promise<void>;
    requestRefund(appointmentId: string, amount: bigint): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    saveTTSAudio(text: string, voiceProfileId: string | null, audioBlob: ExternalBlob, effectSettings: EffectSettings): Promise<string>;
    setStripeConfiguration(config: StripeConfiguration): Promise<void>;
    transform(input: TransformationInput): Promise<TransformationOutput>;
    updateAppointment(appointment: Appointment): Promise<void>;
    updateDailySchedule(schedule: DailySchedule): Promise<void>;
    updateDailyStylistCount(date: string, count: bigint): Promise<void>;
    updateProduct(product: Product): Promise<void>;
    updateStylist(stylist: Stylist): Promise<void>;
    updateStylistLunchBreak(stylistId: string, isOnBreak: boolean, start: string | null, end: string | null): Promise<void>;
    updateTrainingStatus(profileId: string, status: TrainingStatus): Promise<void>;
    updateVoiceProfile(profileId: string, referencePhrases: Array<string>): Promise<void>;
}
import type { Appointment as _Appointment, AppointmentStatus as _AppointmentStatus, EffectSettings as _EffectSettings, ExternalBlob as _ExternalBlob, PaymentStatus as _PaymentStatus, RefundRequest as _RefundRequest, RefundStatus as _RefundStatus, StripeSessionStatus as _StripeSessionStatus, Stylist as _Stylist, TTSAudio as _TTSAudio, TrainingStatus as _TrainingStatus, UserProfile as _UserProfile, UserRole as _UserRole, VoiceEffectPreset as _VoiceEffectPreset, VoiceProfile as _VoiceProfile, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this.uploadFile, this.downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this.uploadFile, this.downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this.uploadFile, this.downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async addDailySchedule(arg0: DailySchedule): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addDailySchedule(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addDailySchedule(arg0);
            return result;
        }
    }
    async addProduct(arg0: Product): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addProduct(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addProduct(arg0);
            return result;
        }
    }
    async addStylist(arg0: Stylist): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addStylist(to_candid_Stylist_n8(this.uploadFile, this.downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addStylist(to_candid_Stylist_n8(this.uploadFile, this.downloadFile, arg0));
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n10(this.uploadFile, this.downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n10(this.uploadFile, this.downloadFile, arg1));
            return result;
        }
    }
    async cancelAppointment(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.cancelAppointment(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.cancelAppointment(arg0);
            return result;
        }
    }
    async createAppointment(arg0: Appointment): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createAppointment(to_candid_Appointment_n12(this.uploadFile, this.downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createAppointment(to_candid_Appointment_n12(this.uploadFile, this.downloadFile, arg0));
            return result;
        }
    }
    async createCheckoutSession(arg0: Array<ShoppingItem>, arg1: string, arg2: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createCheckoutSession(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCheckoutSession(arg0, arg1, arg2);
            return result;
        }
    }
    async createVoiceProfile(arg0: string, arg1: Array<string>): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createVoiceProfile(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createVoiceProfile(arg0, arg1);
            return result;
        }
    }
    async deleteDailySchedule(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteDailySchedule(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteDailySchedule(arg0);
            return result;
        }
    }
    async deleteProduct(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteProduct(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteProduct(arg0);
            return result;
        }
    }
    async deleteStylist(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteStylist(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteStylist(arg0);
            return result;
        }
    }
    async deleteTTSAudio(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTTSAudio(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTTSAudio(arg0);
            return result;
        }
    }
    async deleteVoiceProfile(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteVoiceProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteVoiceProfile(arg0);
            return result;
        }
    }
    async getAppointment(arg0: string): Promise<Appointment | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getAppointment(arg0);
                return from_candid_opt_n18(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAppointment(arg0);
            return from_candid_opt_n18(this.uploadFile, this.downloadFile, result);
        }
    }
    async getAppointments(): Promise<Array<Appointment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAppointments();
                return from_candid_vec_n26(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAppointments();
            return from_candid_vec_n26(this.uploadFile, this.downloadFile, result);
        }
    }
    async getAppointmentsByDate(arg0: string): Promise<Array<Appointment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAppointmentsByDate(arg0);
                return from_candid_vec_n26(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAppointmentsByDate(arg0);
            return from_candid_vec_n26(this.uploadFile, this.downloadFile, result);
        }
    }
    async getAppointmentsByDateAndTimeSlot(arg0: string, arg1: string): Promise<Array<Appointment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAppointmentsByDateAndTimeSlot(arg0, arg1);
                return from_candid_vec_n26(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAppointmentsByDateAndTimeSlot(arg0, arg1);
            return from_candid_vec_n26(this.uploadFile, this.downloadFile, result);
        }
    }
    async getAppointmentsByDateRange(arg0: string, arg1: string): Promise<Array<Appointment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAppointmentsByDateRange(arg0, arg1);
                return from_candid_vec_n26(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAppointmentsByDateRange(arg0, arg1);
            return from_candid_vec_n26(this.uploadFile, this.downloadFile, result);
        }
    }
    async getAppointmentsByDateRangeAndStatus(arg0: string, arg1: string, arg2: AppointmentStatus): Promise<Array<Appointment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAppointmentsByDateRangeAndStatus(arg0, arg1, to_candid_AppointmentStatus_n14(this.uploadFile, this.downloadFile, arg2));
                return from_candid_vec_n26(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAppointmentsByDateRangeAndStatus(arg0, arg1, to_candid_AppointmentStatus_n14(this.uploadFile, this.downloadFile, arg2));
            return from_candid_vec_n26(this.uploadFile, this.downloadFile, result);
        }
    }
    async getAppointmentsByDateRangeAndTimeSlot(arg0: string, arg1: string, arg2: string): Promise<Array<Appointment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAppointmentsByDateRangeAndTimeSlot(arg0, arg1, arg2);
                return from_candid_vec_n26(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAppointmentsByDateRangeAndTimeSlot(arg0, arg1, arg2);
            return from_candid_vec_n26(this.uploadFile, this.downloadFile, result);
        }
    }
    async getAppointmentsByPhone(arg0: string): Promise<Array<Appointment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAppointmentsByPhone(arg0);
                return from_candid_vec_n26(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAppointmentsByPhone(arg0);
            return from_candid_vec_n26(this.uploadFile, this.downloadFile, result);
        }
    }
    async getAppointmentsByPhoneAndDateRange(arg0: string, arg1: string, arg2: string): Promise<Array<Appointment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAppointmentsByPhoneAndDateRange(arg0, arg1, arg2);
                return from_candid_vec_n26(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAppointmentsByPhoneAndDateRange(arg0, arg1, arg2);
            return from_candid_vec_n26(this.uploadFile, this.downloadFile, result);
        }
    }
    async getAppointmentsByStatus(arg0: AppointmentStatus): Promise<Array<Appointment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAppointmentsByStatus(to_candid_AppointmentStatus_n14(this.uploadFile, this.downloadFile, arg0));
                return from_candid_vec_n26(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAppointmentsByStatus(to_candid_AppointmentStatus_n14(this.uploadFile, this.downloadFile, arg0));
            return from_candid_vec_n26(this.uploadFile, this.downloadFile, result);
        }
    }
    async getAppointmentsByStatusAndDate(arg0: AppointmentStatus, arg1: string): Promise<Array<Appointment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAppointmentsByStatusAndDate(to_candid_AppointmentStatus_n14(this.uploadFile, this.downloadFile, arg0), arg1);
                return from_candid_vec_n26(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAppointmentsByStatusAndDate(to_candid_AppointmentStatus_n14(this.uploadFile, this.downloadFile, arg0), arg1);
            return from_candid_vec_n26(this.uploadFile, this.downloadFile, result);
        }
    }
    async getAppointmentsByStatusAndDateRange(arg0: AppointmentStatus, arg1: string, arg2: string): Promise<Array<Appointment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAppointmentsByStatusAndDateRange(to_candid_AppointmentStatus_n14(this.uploadFile, this.downloadFile, arg0), arg1, arg2);
                return from_candid_vec_n26(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAppointmentsByStatusAndDateRange(to_candid_AppointmentStatus_n14(this.uploadFile, this.downloadFile, arg0), arg1, arg2);
            return from_candid_vec_n26(this.uploadFile, this.downloadFile, result);
        }
    }
    async getAppointmentsByStatusAndTimeSlot(arg0: AppointmentStatus, arg1: string): Promise<Array<Appointment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAppointmentsByStatusAndTimeSlot(to_candid_AppointmentStatus_n14(this.uploadFile, this.downloadFile, arg0), arg1);
                return from_candid_vec_n26(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAppointmentsByStatusAndTimeSlot(to_candid_AppointmentStatus_n14(this.uploadFile, this.downloadFile, arg0), arg1);
            return from_candid_vec_n26(this.uploadFile, this.downloadFile, result);
        }
    }
    async getAppointmentsByStatusAndTimeSlotAndDateRange(arg0: AppointmentStatus, arg1: string, arg2: string, arg3: string): Promise<Array<Appointment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAppointmentsByStatusAndTimeSlotAndDateRange(to_candid_AppointmentStatus_n14(this.uploadFile, this.downloadFile, arg0), arg1, arg2, arg3);
                return from_candid_vec_n26(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAppointmentsByStatusAndTimeSlotAndDateRange(to_candid_AppointmentStatus_n14(this.uploadFile, this.downloadFile, arg0), arg1, arg2, arg3);
            return from_candid_vec_n26(this.uploadFile, this.downloadFile, result);
        }
    }
    async getAppointmentsByStylist(arg0: string): Promise<Array<Appointment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAppointmentsByStylist(arg0);
                return from_candid_vec_n26(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAppointmentsByStylist(arg0);
            return from_candid_vec_n26(this.uploadFile, this.downloadFile, result);
        }
    }
    async getAppointmentsByStylistAndDateRange(arg0: string, arg1: string, arg2: string): Promise<Array<Appointment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAppointmentsByStylistAndDateRange(arg0, arg1, arg2);
                return from_candid_vec_n26(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAppointmentsByStylistAndDateRange(arg0, arg1, arg2);
            return from_candid_vec_n26(this.uploadFile, this.downloadFile, result);
        }
    }
    async getAppointmentsByTimeSlot(arg0: string): Promise<Array<Appointment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAppointmentsByTimeSlot(arg0);
                return from_candid_vec_n26(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAppointmentsByTimeSlot(arg0);
            return from_candid_vec_n26(this.uploadFile, this.downloadFile, result);
        }
    }
    async getAvailableDays(): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAvailableDays();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAvailableDays();
            return result;
        }
    }
    async getAvailableSlotsForDay(arg0: string): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAvailableSlotsForDay(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAvailableSlotsForDay(arg0);
            return result;
        }
    }
    async getAvailableSlotsForStylist(arg0: string, arg1: string): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAvailableSlotsForStylist(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAvailableSlotsForStylist(arg0, arg1);
            return result;
        }
    }
    async getAvailableStylistsForSlot(arg0: string, arg1: string): Promise<Array<Stylist>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAvailableStylistsForSlot(arg0, arg1);
                return from_candid_vec_n27(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAvailableStylistsForSlot(arg0, arg1);
            return from_candid_vec_n27(this.uploadFile, this.downloadFile, result);
        }
    }
    async getAvailableTimeSlots(arg0: string): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAvailableTimeSlots(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAvailableTimeSlots(arg0);
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n30(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n30(this.uploadFile, this.downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n31(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n31(this.uploadFile, this.downloadFile, result);
        }
    }
    async getClosedDays(): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getClosedDays();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getClosedDays();
            return result;
        }
    }
    async getDailySchedules(): Promise<Array<DailySchedule>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDailySchedules();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDailySchedules();
            return result;
        }
    }
    async getLunchBreaksForDate(arg0: string): Promise<Array<Stylist>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLunchBreaksForDate(arg0);
                return from_candid_vec_n27(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLunchBreaksForDate(arg0);
            return from_candid_vec_n27(this.uploadFile, this.downloadFile, result);
        }
    }
    async getProducts(): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.getProducts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProducts();
            return result;
        }
    }
    async getRefundRequests(): Promise<Array<RefundRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRefundRequests();
                return from_candid_vec_n33(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRefundRequests();
            return from_candid_vec_n33(this.uploadFile, this.downloadFile, result);
        }
    }
    async getStripeSessionStatus(arg0: string): Promise<StripeSessionStatus> {
        if (this.processError) {
            try {
                const result = await this.actor.getStripeSessionStatus(arg0);
                return from_candid_StripeSessionStatus_n39(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStripeSessionStatus(arg0);
            return from_candid_StripeSessionStatus_n39(this.uploadFile, this.downloadFile, result);
        }
    }
    async getStylistAvailability(arg0: string): Promise<Array<Stylist>> {
        if (this.processError) {
            try {
                const result = await this.actor.getStylistAvailability(arg0);
                return from_candid_vec_n27(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStylistAvailability(arg0);
            return from_candid_vec_n27(this.uploadFile, this.downloadFile, result);
        }
    }
    async getStylists(): Promise<Array<Stylist>> {
        if (this.processError) {
            try {
                const result = await this.actor.getStylists();
                return from_candid_vec_n27(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStylists();
            return from_candid_vec_n27(this.uploadFile, this.downloadFile, result);
        }
    }
    async getTTSAudio(): Promise<Array<TTSAudio>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTTSAudio();
                return from_candid_vec_n42(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTTSAudio();
            return from_candid_vec_n42(this.uploadFile, this.downloadFile, result);
        }
    }
    async getTTSAudioById(arg0: string): Promise<TTSAudio | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getTTSAudioById(arg0);
                return from_candid_opt_n51(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTTSAudioById(arg0);
            return from_candid_opt_n51(this.uploadFile, this.downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n30(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n30(this.uploadFile, this.downloadFile, result);
        }
    }
    async getVoiceProfile(arg0: string): Promise<VoiceProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getVoiceProfile(arg0);
                return from_candid_opt_n52(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVoiceProfile(arg0);
            return from_candid_opt_n52(this.uploadFile, this.downloadFile, result);
        }
    }
    async getVoiceProfiles(): Promise<Array<VoiceProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getVoiceProfiles();
                return from_candid_vec_n58(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVoiceProfiles();
            return from_candid_vec_n58(this.uploadFile, this.downloadFile, result);
        }
    }
    async initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initializeAccessControl();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isStripeConfigured(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isStripeConfigured();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isStripeConfigured();
            return result;
        }
    }
    async processRefund(arg0: string, arg1: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.processRefund(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.processRefund(arg0, arg1);
            return result;
        }
    }
    async requestRefund(arg0: string, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.requestRefund(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.requestRefund(arg0, arg1);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async saveTTSAudio(arg0: string, arg1: string | null, arg2: ExternalBlob, arg3: EffectSettings): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.saveTTSAudio(arg0, to_candid_opt_n59(this.uploadFile, this.downloadFile, arg1), await to_candid_ExternalBlob_n60(this.uploadFile, this.downloadFile, arg2), to_candid_EffectSettings_n61(this.uploadFile, this.downloadFile, arg3));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveTTSAudio(arg0, to_candid_opt_n59(this.uploadFile, this.downloadFile, arg1), await to_candid_ExternalBlob_n60(this.uploadFile, this.downloadFile, arg2), to_candid_EffectSettings_n61(this.uploadFile, this.downloadFile, arg3));
            return result;
        }
    }
    async setStripeConfiguration(arg0: StripeConfiguration): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setStripeConfiguration(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setStripeConfiguration(arg0);
            return result;
        }
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
    async updateAppointment(arg0: Appointment): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateAppointment(to_candid_Appointment_n12(this.uploadFile, this.downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateAppointment(to_candid_Appointment_n12(this.uploadFile, this.downloadFile, arg0));
            return result;
        }
    }
    async updateDailySchedule(arg0: DailySchedule): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateDailySchedule(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateDailySchedule(arg0);
            return result;
        }
    }
    async updateDailyStylistCount(arg0: string, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateDailyStylistCount(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateDailyStylistCount(arg0, arg1);
            return result;
        }
    }
    async updateProduct(arg0: Product): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProduct(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProduct(arg0);
            return result;
        }
    }
    async updateStylist(arg0: Stylist): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateStylist(to_candid_Stylist_n8(this.uploadFile, this.downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateStylist(to_candid_Stylist_n8(this.uploadFile, this.downloadFile, arg0));
            return result;
        }
    }
    async updateStylistLunchBreak(arg0: string, arg1: boolean, arg2: string | null, arg3: string | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateStylistLunchBreak(arg0, arg1, to_candid_opt_n59(this.uploadFile, this.downloadFile, arg2), to_candid_opt_n59(this.uploadFile, this.downloadFile, arg3));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateStylistLunchBreak(arg0, arg1, to_candid_opt_n59(this.uploadFile, this.downloadFile, arg2), to_candid_opt_n59(this.uploadFile, this.downloadFile, arg3));
            return result;
        }
    }
    async updateTrainingStatus(arg0: string, arg1: TrainingStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTrainingStatus(arg0, to_candid_TrainingStatus_n65(this.uploadFile, this.downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTrainingStatus(arg0, to_candid_TrainingStatus_n65(this.uploadFile, this.downloadFile, arg1));
            return result;
        }
    }
    async updateVoiceProfile(arg0: string, arg1: Array<string>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateVoiceProfile(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateVoiceProfile(arg0, arg1);
            return result;
        }
    }
}
function from_candid_AppointmentStatus_n21(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AppointmentStatus): AppointmentStatus {
    return from_candid_variant_n22(uploadFile, downloadFile, value);
}
function from_candid_Appointment_n19(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Appointment): Appointment {
    return from_candid_record_n20(uploadFile, downloadFile, value);
}
function from_candid_EffectSettings_n46(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _EffectSettings): EffectSettings {
    return from_candid_record_n47(uploadFile, downloadFile, value);
}
async function from_candid_ExternalBlob_n45(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await downloadFile(value);
}
function from_candid_PaymentStatus_n24(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaymentStatus): PaymentStatus {
    return from_candid_variant_n25(uploadFile, downloadFile, value);
}
function from_candid_RefundRequest_n34(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RefundRequest): RefundRequest {
    return from_candid_record_n35(uploadFile, downloadFile, value);
}
function from_candid_RefundStatus_n36(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RefundStatus): RefundStatus {
    return from_candid_variant_n37(uploadFile, downloadFile, value);
}
function from_candid_StripeSessionStatus_n39(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StripeSessionStatus): StripeSessionStatus {
    return from_candid_variant_n40(uploadFile, downloadFile, value);
}
function from_candid_Stylist_n28(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Stylist): Stylist {
    return from_candid_record_n29(uploadFile, downloadFile, value);
}
async function from_candid_TTSAudio_n43(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TTSAudio): Promise<TTSAudio> {
    return await from_candid_record_n44(uploadFile, downloadFile, value);
}
function from_candid_TrainingStatus_n56(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TrainingStatus): TrainingStatus {
    return from_candid_variant_n57(uploadFile, downloadFile, value);
}
function from_candid_UserRole_n31(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n32(uploadFile, downloadFile, value);
}
function from_candid_VoiceEffectPreset_n49(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _VoiceEffectPreset): VoiceEffectPreset {
    return from_candid_variant_n50(uploadFile, downloadFile, value);
}
async function from_candid_VoiceProfile_n53(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _VoiceProfile): Promise<VoiceProfile> {
    return await from_candid_record_n54(uploadFile, downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(uploadFile, downloadFile, value);
}
function from_candid_opt_n18(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Appointment]): Appointment | null {
    return value.length === 0 ? null : from_candid_Appointment_n19(uploadFile, downloadFile, value[0]);
}
function from_candid_opt_n23(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n30(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n38(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n48(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_VoiceEffectPreset]): VoiceEffectPreset | null {
    return value.length === 0 ? null : from_candid_VoiceEffectPreset_n49(uploadFile, downloadFile, value[0]);
}
async function from_candid_opt_n51(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_TTSAudio]): Promise<TTSAudio | null> {
    return value.length === 0 ? null : await from_candid_TTSAudio_n43(uploadFile, downloadFile, value[0]);
}
async function from_candid_opt_n52(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_VoiceProfile]): Promise<VoiceProfile | null> {
    return value.length === 0 ? null : await from_candid_VoiceProfile_n53(uploadFile, downloadFile, value[0]);
}
async function from_candid_opt_n55(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExternalBlob]): Promise<ExternalBlob | null> {
    return value.length === 0 ? null : await from_candid_ExternalBlob_n45(uploadFile, downloadFile, value[0]);
}
function from_candid_opt_n6(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n20(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: _AppointmentStatus;
    depositAmount: bigint;
    assignedStylist: [] | [string];
    paymentStatus: _PaymentStatus;
    stylistRequest: [] | [string];
    date: string;
    createdAt: bigint;
    parentPhone: string;
    updatedAt: bigint;
    childFirstName: string;
    childLastName: string;
    refundEligible: boolean;
    timeSlot: string;
}): {
    id: string;
    status: AppointmentStatus;
    depositAmount: bigint;
    assignedStylist?: string;
    paymentStatus: PaymentStatus;
    stylistRequest?: string;
    date: string;
    createdAt: bigint;
    parentPhone: string;
    updatedAt: bigint;
    childFirstName: string;
    childLastName: string;
    refundEligible: boolean;
    timeSlot: string;
} {
    return {
        id: value.id,
        status: from_candid_AppointmentStatus_n21(uploadFile, downloadFile, value.status),
        depositAmount: value.depositAmount,
        assignedStylist: record_opt_to_undefined(from_candid_opt_n23(uploadFile, downloadFile, value.assignedStylist)),
        paymentStatus: from_candid_PaymentStatus_n24(uploadFile, downloadFile, value.paymentStatus),
        stylistRequest: record_opt_to_undefined(from_candid_opt_n23(uploadFile, downloadFile, value.stylistRequest)),
        date: value.date,
        createdAt: value.createdAt,
        parentPhone: value.parentPhone,
        updatedAt: value.updatedAt,
        childFirstName: value.childFirstName,
        childLastName: value.childLastName,
        refundEligible: value.refundEligible,
        timeSlot: value.timeSlot
    };
}
function from_candid_record_n29(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    lunchBreakStart: [] | [string];
    name: string;
    isAvailable: boolean;
    lunchBreakEnd: [] | [string];
    isOnLunchBreak: boolean;
}): {
    id: string;
    lunchBreakStart?: string;
    name: string;
    isAvailable: boolean;
    lunchBreakEnd?: string;
    isOnLunchBreak: boolean;
} {
    return {
        id: value.id,
        lunchBreakStart: record_opt_to_undefined(from_candid_opt_n23(uploadFile, downloadFile, value.lunchBreakStart)),
        name: value.name,
        isAvailable: value.isAvailable,
        lunchBreakEnd: record_opt_to_undefined(from_candid_opt_n23(uploadFile, downloadFile, value.lunchBreakEnd)),
        isOnLunchBreak: value.isOnLunchBreak
    };
}
function from_candid_record_n35(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _RefundStatus;
    processedAt: [] | [bigint];
    amount: bigint;
    appointmentId: string;
    requestedAt: bigint;
}): {
    status: RefundStatus;
    processedAt?: bigint;
    amount: bigint;
    appointmentId: string;
    requestedAt: bigint;
} {
    return {
        status: from_candid_RefundStatus_n36(uploadFile, downloadFile, value.status),
        processedAt: record_opt_to_undefined(from_candid_opt_n38(uploadFile, downloadFile, value.processedAt)),
        amount: value.amount,
        appointmentId: value.appointmentId,
        requestedAt: value.requestedAt
    };
}
function from_candid_record_n41(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    userPrincipal: [] | [string];
    response: string;
}): {
    userPrincipal?: string;
    response: string;
} {
    return {
        userPrincipal: record_opt_to_undefined(from_candid_opt_n23(uploadFile, downloadFile, value.userPrincipal)),
        response: value.response
    };
}
async function from_candid_record_n44(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    createdAt: bigint;
    text: string;
    audioBlob: _ExternalBlob;
    voiceProfileId: [] | [string];
    effectSettings: _EffectSettings;
}): Promise<{
    id: string;
    createdAt: bigint;
    text: string;
    audioBlob: ExternalBlob;
    voiceProfileId?: string;
    effectSettings: EffectSettings;
}> {
    return {
        id: value.id,
        createdAt: value.createdAt,
        text: value.text,
        audioBlob: await from_candid_ExternalBlob_n45(uploadFile, downloadFile, value.audioBlob),
        voiceProfileId: record_opt_to_undefined(from_candid_opt_n23(uploadFile, downloadFile, value.voiceProfileId)),
        effectSettings: from_candid_EffectSettings_n46(uploadFile, downloadFile, value.effectSettings)
    };
}
function from_candid_record_n47(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    tone: number;
    speed: number;
    preset: [] | [_VoiceEffectPreset];
    pitch: number;
}): {
    tone: number;
    speed: number;
    preset?: VoiceEffectPreset;
    pitch: number;
} {
    return {
        tone: value.tone,
        speed: value.speed,
        preset: record_opt_to_undefined(from_candid_opt_n48(uploadFile, downloadFile, value.preset)),
        pitch: value.pitch
    };
}
function from_candid_record_n5(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(uploadFile, downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(uploadFile, downloadFile, value.topped_up_amount))
    };
}
async function from_candid_record_n54(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    userId: Principal;
    name: string;
    createdAt: bigint;
    audioBlob: [] | [_ExternalBlob];
    updatedAt: bigint;
    trainingStatus: _TrainingStatus;
    referencePhrases: Array<string>;
}): Promise<{
    id: string;
    userId: Principal;
    name: string;
    createdAt: bigint;
    audioBlob?: ExternalBlob;
    updatedAt: bigint;
    trainingStatus: TrainingStatus;
    referencePhrases: Array<string>;
}> {
    return {
        id: value.id,
        userId: value.userId,
        name: value.name,
        createdAt: value.createdAt,
        audioBlob: record_opt_to_undefined(await from_candid_opt_n55(uploadFile, downloadFile, value.audioBlob)),
        updatedAt: value.updatedAt,
        trainingStatus: from_candid_TrainingStatus_n56(uploadFile, downloadFile, value.trainingStatus),
        referencePhrases: value.referencePhrases
    };
}
function from_candid_variant_n22(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    cancelled: null;
} | {
    completed: null;
} | {
    booked: null;
} | {
    confirmed: null;
}): AppointmentStatus {
    return "cancelled" in value ? AppointmentStatus.cancelled : "completed" in value ? AppointmentStatus.completed : "booked" in value ? AppointmentStatus.booked : "confirmed" in value ? AppointmentStatus.confirmed : value;
}
function from_candid_variant_n25(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    paid: null;
} | {
    refunded: null;
} | {
    notRequired: null;
}): PaymentStatus {
    return "pending" in value ? PaymentStatus.pending : "paid" in value ? PaymentStatus.paid : "refunded" in value ? PaymentStatus.refunded : "notRequired" in value ? PaymentStatus.notRequired : value;
}
function from_candid_variant_n32(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n37(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
} | {
    processed: null;
}): RefundStatus {
    return "pending" in value ? RefundStatus.pending : "approved" in value ? RefundStatus.approved : "rejected" in value ? RefundStatus.rejected : "processed" in value ? RefundStatus.processed : value;
}
function from_candid_variant_n40(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    completed: {
        userPrincipal: [] | [string];
        response: string;
    };
} | {
    failed: {
        error: string;
    };
}): {
    __kind__: "completed";
    completed: {
        userPrincipal?: string;
        response: string;
    };
} | {
    __kind__: "failed";
    failed: {
        error: string;
    };
} {
    return "completed" in value ? {
        __kind__: "completed",
        completed: from_candid_record_n41(uploadFile, downloadFile, value.completed)
    } : "failed" in value ? {
        __kind__: "failed",
        failed: value.failed
    } : value;
}
function from_candid_variant_n50(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    reverb: null;
} | {
    alien: null;
} | {
    deep: null;
} | {
    echo: null;
} | {
    robotic: null;
} | {
    chipmunk: null;
}): VoiceEffectPreset {
    return "reverb" in value ? VoiceEffectPreset.reverb : "alien" in value ? VoiceEffectPreset.alien : "deep" in value ? VoiceEffectPreset.deep : "echo" in value ? VoiceEffectPreset.echo : "robotic" in value ? VoiceEffectPreset.robotic : "chipmunk" in value ? VoiceEffectPreset.chipmunk : value;
}
function from_candid_variant_n57(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    notStarted: null;
} | {
    completed: null;
} | {
    inProgress: null;
} | {
    failed: null;
}): TrainingStatus {
    return "notStarted" in value ? TrainingStatus.notStarted : "completed" in value ? TrainingStatus.completed : "inProgress" in value ? TrainingStatus.inProgress : "failed" in value ? TrainingStatus.failed : value;
}
function from_candid_vec_n26(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Appointment>): Array<Appointment> {
    return value.map((x)=>from_candid_Appointment_n19(uploadFile, downloadFile, x));
}
function from_candid_vec_n27(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Stylist>): Array<Stylist> {
    return value.map((x)=>from_candid_Stylist_n28(uploadFile, downloadFile, x));
}
function from_candid_vec_n33(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_RefundRequest>): Array<RefundRequest> {
    return value.map((x)=>from_candid_RefundRequest_n34(uploadFile, downloadFile, x));
}
async function from_candid_vec_n42(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_TTSAudio>): Promise<Array<TTSAudio>> {
    return await Promise.all(value.map(async (x)=>await from_candid_TTSAudio_n43(uploadFile, downloadFile, x)));
}
async function from_candid_vec_n58(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_VoiceProfile>): Promise<Array<VoiceProfile>> {
    return await Promise.all(value.map(async (x)=>await from_candid_VoiceProfile_n53(uploadFile, downloadFile, x)));
}
function to_candid_AppointmentStatus_n14(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AppointmentStatus): _AppointmentStatus {
    return to_candid_variant_n15(uploadFile, downloadFile, value);
}
function to_candid_Appointment_n12(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Appointment): _Appointment {
    return to_candid_record_n13(uploadFile, downloadFile, value);
}
function to_candid_EffectSettings_n61(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EffectSettings): _EffectSettings {
    return to_candid_record_n62(uploadFile, downloadFile, value);
}
async function to_candid_ExternalBlob_n60(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await uploadFile(value);
}
function to_candid_PaymentStatus_n16(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentStatus): _PaymentStatus {
    return to_candid_variant_n17(uploadFile, downloadFile, value);
}
function to_candid_Stylist_n8(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Stylist): _Stylist {
    return to_candid_record_n9(uploadFile, downloadFile, value);
}
function to_candid_TrainingStatus_n65(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TrainingStatus): _TrainingStatus {
    return to_candid_variant_n66(uploadFile, downloadFile, value);
}
function to_candid_UserRole_n10(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n11(uploadFile, downloadFile, value);
}
function to_candid_VoiceEffectPreset_n63(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: VoiceEffectPreset): _VoiceEffectPreset {
    return to_candid_variant_n64(uploadFile, downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(uploadFile, downloadFile, value);
}
function to_candid_opt_n1(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(uploadFile, downloadFile, value));
}
function to_candid_opt_n59(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n13(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: AppointmentStatus;
    depositAmount: bigint;
    assignedStylist?: string;
    paymentStatus: PaymentStatus;
    stylistRequest?: string;
    date: string;
    createdAt: bigint;
    parentPhone: string;
    updatedAt: bigint;
    childFirstName: string;
    childLastName: string;
    refundEligible: boolean;
    timeSlot: string;
}): {
    id: string;
    status: _AppointmentStatus;
    depositAmount: bigint;
    assignedStylist: [] | [string];
    paymentStatus: _PaymentStatus;
    stylistRequest: [] | [string];
    date: string;
    createdAt: bigint;
    parentPhone: string;
    updatedAt: bigint;
    childFirstName: string;
    childLastName: string;
    refundEligible: boolean;
    timeSlot: string;
} {
    return {
        id: value.id,
        status: to_candid_AppointmentStatus_n14(uploadFile, downloadFile, value.status),
        depositAmount: value.depositAmount,
        assignedStylist: value.assignedStylist ? candid_some(value.assignedStylist) : candid_none(),
        paymentStatus: to_candid_PaymentStatus_n16(uploadFile, downloadFile, value.paymentStatus),
        stylistRequest: value.stylistRequest ? candid_some(value.stylistRequest) : candid_none(),
        date: value.date,
        createdAt: value.createdAt,
        parentPhone: value.parentPhone,
        updatedAt: value.updatedAt,
        childFirstName: value.childFirstName,
        childLastName: value.childLastName,
        refundEligible: value.refundEligible,
        timeSlot: value.timeSlot
    };
}
function to_candid_record_n3(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n62(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    tone: number;
    speed: number;
    preset?: VoiceEffectPreset;
    pitch: number;
}): {
    tone: number;
    speed: number;
    preset: [] | [_VoiceEffectPreset];
    pitch: number;
} {
    return {
        tone: value.tone,
        speed: value.speed,
        preset: value.preset ? candid_some(to_candid_VoiceEffectPreset_n63(uploadFile, downloadFile, value.preset)) : candid_none(),
        pitch: value.pitch
    };
}
function to_candid_record_n9(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    lunchBreakStart?: string;
    name: string;
    isAvailable: boolean;
    lunchBreakEnd?: string;
    isOnLunchBreak: boolean;
}): {
    id: string;
    lunchBreakStart: [] | [string];
    name: string;
    isAvailable: boolean;
    lunchBreakEnd: [] | [string];
    isOnLunchBreak: boolean;
} {
    return {
        id: value.id,
        lunchBreakStart: value.lunchBreakStart ? candid_some(value.lunchBreakStart) : candid_none(),
        name: value.name,
        isAvailable: value.isAvailable,
        lunchBreakEnd: value.lunchBreakEnd ? candid_some(value.lunchBreakEnd) : candid_none(),
        isOnLunchBreak: value.isOnLunchBreak
    };
}
function to_candid_variant_n11(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n15(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AppointmentStatus): {
    cancelled: null;
} | {
    completed: null;
} | {
    booked: null;
} | {
    confirmed: null;
} {
    return value == AppointmentStatus.cancelled ? {
        cancelled: null
    } : value == AppointmentStatus.completed ? {
        completed: null
    } : value == AppointmentStatus.booked ? {
        booked: null
    } : value == AppointmentStatus.confirmed ? {
        confirmed: null
    } : value;
}
function to_candid_variant_n17(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentStatus): {
    pending: null;
} | {
    paid: null;
} | {
    refunded: null;
} | {
    notRequired: null;
} {
    return value == PaymentStatus.pending ? {
        pending: null
    } : value == PaymentStatus.paid ? {
        paid: null
    } : value == PaymentStatus.refunded ? {
        refunded: null
    } : value == PaymentStatus.notRequired ? {
        notRequired: null
    } : value;
}
function to_candid_variant_n64(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: VoiceEffectPreset): {
    reverb: null;
} | {
    alien: null;
} | {
    deep: null;
} | {
    echo: null;
} | {
    robotic: null;
} | {
    chipmunk: null;
} {
    return value == VoiceEffectPreset.reverb ? {
        reverb: null
    } : value == VoiceEffectPreset.alien ? {
        alien: null
    } : value == VoiceEffectPreset.deep ? {
        deep: null
    } : value == VoiceEffectPreset.echo ? {
        echo: null
    } : value == VoiceEffectPreset.robotic ? {
        robotic: null
    } : value == VoiceEffectPreset.chipmunk ? {
        chipmunk: null
    } : value;
}
function to_candid_variant_n66(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TrainingStatus): {
    notStarted: null;
} | {
    completed: null;
} | {
    inProgress: null;
} | {
    failed: null;
} {
    return value == TrainingStatus.notStarted ? {
        notStarted: null
    } : value == TrainingStatus.completed ? {
        completed: null
    } : value == TrainingStatus.inProgress ? {
        inProgress: null
    } : value == TrainingStatus.failed ? {
        failed: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, uploadFile, downloadFile, options.processError);
}