/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @dfinity/caffeine-bindgen@0.1.0-beta.7.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const DailySchedule = IDL.Record({
  'lunchBreaks' : IDL.Vec(IDL.Text),
  'date' : IDL.Text,
  'isOpen' : IDL.Bool,
  'availableStylists' : IDL.Nat,
});
export const Product = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'currency' : IDL.Text,
  'priceInCents' : IDL.Nat,
});
export const Stylist = IDL.Record({
  'id' : IDL.Text,
  'lunchBreakStart' : IDL.Opt(IDL.Text),
  'name' : IDL.Text,
  'isAvailable' : IDL.Bool,
  'lunchBreakEnd' : IDL.Opt(IDL.Text),
  'isOnLunchBreak' : IDL.Bool,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const AppointmentStatus = IDL.Variant({
  'cancelled' : IDL.Null,
  'completed' : IDL.Null,
  'booked' : IDL.Null,
  'confirmed' : IDL.Null,
});
export const PaymentStatus = IDL.Variant({
  'pending' : IDL.Null,
  'paid' : IDL.Null,
  'refunded' : IDL.Null,
  'notRequired' : IDL.Null,
});
export const Appointment = IDL.Record({
  'id' : IDL.Text,
  'status' : AppointmentStatus,
  'depositAmount' : IDL.Nat,
  'assignedStylist' : IDL.Opt(IDL.Text),
  'paymentStatus' : PaymentStatus,
  'stylistRequest' : IDL.Opt(IDL.Text),
  'date' : IDL.Text,
  'createdAt' : IDL.Int,
  'parentPhone' : IDL.Text,
  'updatedAt' : IDL.Int,
  'childFirstName' : IDL.Text,
  'childLastName' : IDL.Text,
  'refundEligible' : IDL.Bool,
  'timeSlot' : IDL.Text,
});
export const ShoppingItem = IDL.Record({
  'productName' : IDL.Text,
  'currency' : IDL.Text,
  'quantity' : IDL.Nat,
  'priceInCents' : IDL.Nat,
  'productDescription' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'phone' : IDL.Text,
});
export const RefundStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
  'processed' : IDL.Null,
});
export const RefundRequest = IDL.Record({
  'status' : RefundStatus,
  'processedAt' : IDL.Opt(IDL.Int),
  'amount' : IDL.Nat,
  'appointmentId' : IDL.Text,
  'requestedAt' : IDL.Int,
});
export const StripeSessionStatus = IDL.Variant({
  'completed' : IDL.Record({
    'userPrincipal' : IDL.Opt(IDL.Text),
    'response' : IDL.Text,
  }),
  'failed' : IDL.Record({ 'error' : IDL.Text }),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const VoiceEffectPreset = IDL.Variant({
  'reverb' : IDL.Null,
  'alien' : IDL.Null,
  'deep' : IDL.Null,
  'echo' : IDL.Null,
  'robotic' : IDL.Null,
  'chipmunk' : IDL.Null,
});
export const EffectSettings = IDL.Record({
  'tone' : IDL.Float64,
  'speed' : IDL.Float64,
  'preset' : IDL.Opt(VoiceEffectPreset),
  'pitch' : IDL.Float64,
});
export const TTSAudio = IDL.Record({
  'id' : IDL.Text,
  'createdAt' : IDL.Int,
  'text' : IDL.Text,
  'audioBlob' : ExternalBlob,
  'voiceProfileId' : IDL.Opt(IDL.Text),
  'effectSettings' : EffectSettings,
});
export const TrainingStatus = IDL.Variant({
  'notStarted' : IDL.Null,
  'completed' : IDL.Null,
  'inProgress' : IDL.Null,
  'failed' : IDL.Null,
});
export const VoiceProfile = IDL.Record({
  'id' : IDL.Text,
  'userId' : IDL.Principal,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'audioBlob' : IDL.Opt(ExternalBlob),
  'updatedAt' : IDL.Int,
  'trainingStatus' : TrainingStatus,
  'referencePhrases' : IDL.Vec(IDL.Text),
});
export const StripeConfiguration = IDL.Record({
  'allowedCountries' : IDL.Vec(IDL.Text),
  'secretKey' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'addDailySchedule' : IDL.Func([DailySchedule], [], []),
  'addProduct' : IDL.Func([Product], [], []),
  'addStylist' : IDL.Func([Stylist], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'cancelAppointment' : IDL.Func([IDL.Text], [], []),
  'createAppointment' : IDL.Func([Appointment], [], []),
  'createCheckoutSession' : IDL.Func(
      [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'createVoiceProfile' : IDL.Func(
      [IDL.Text, IDL.Vec(IDL.Text)],
      [IDL.Text],
      [],
    ),
  'deleteDailySchedule' : IDL.Func([IDL.Text], [], []),
  'deleteProduct' : IDL.Func([IDL.Text], [], []),
  'deleteStylist' : IDL.Func([IDL.Text], [], []),
  'deleteTTSAudio' : IDL.Func([IDL.Text], [], []),
  'deleteVoiceProfile' : IDL.Func([IDL.Text], [], []),
  'getAppointment' : IDL.Func([IDL.Text], [IDL.Opt(Appointment)], ['query']),
  'getAppointments' : IDL.Func([], [IDL.Vec(Appointment)], ['query']),
  'getAppointmentsByDate' : IDL.Func([IDL.Text], [IDL.Vec(Appointment)], []),
  'getAppointmentsByDateAndTimeSlot' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Vec(Appointment)],
      [],
    ),
  'getAppointmentsByDateRange' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Vec(Appointment)],
      [],
    ),
  'getAppointmentsByDateRangeAndStatus' : IDL.Func(
      [IDL.Text, IDL.Text, AppointmentStatus],
      [IDL.Vec(Appointment)],
      [],
    ),
  'getAppointmentsByDateRangeAndTimeSlot' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [IDL.Vec(Appointment)],
      [],
    ),
  'getAppointmentsByPhone' : IDL.Func([IDL.Text], [IDL.Vec(Appointment)], []),
  'getAppointmentsByPhoneAndDateRange' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [IDL.Vec(Appointment)],
      [],
    ),
  'getAppointmentsByStatus' : IDL.Func(
      [AppointmentStatus],
      [IDL.Vec(Appointment)],
      [],
    ),
  'getAppointmentsByStatusAndDate' : IDL.Func(
      [AppointmentStatus, IDL.Text],
      [IDL.Vec(Appointment)],
      [],
    ),
  'getAppointmentsByStatusAndDateRange' : IDL.Func(
      [AppointmentStatus, IDL.Text, IDL.Text],
      [IDL.Vec(Appointment)],
      [],
    ),
  'getAppointmentsByStatusAndTimeSlot' : IDL.Func(
      [AppointmentStatus, IDL.Text],
      [IDL.Vec(Appointment)],
      [],
    ),
  'getAppointmentsByStatusAndTimeSlotAndDateRange' : IDL.Func(
      [AppointmentStatus, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Vec(Appointment)],
      [],
    ),
  'getAppointmentsByStylist' : IDL.Func([IDL.Text], [IDL.Vec(Appointment)], []),
  'getAppointmentsByStylistAndDateRange' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [IDL.Vec(Appointment)],
      [],
    ),
  'getAppointmentsByTimeSlot' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Appointment)],
      [],
    ),
  'getAvailableDays' : IDL.Func([], [IDL.Vec(IDL.Text)], []),
  'getAvailableSlotsForDay' : IDL.Func([IDL.Text], [IDL.Vec(IDL.Text)], []),
  'getAvailableSlotsForStylist' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Vec(IDL.Text)],
      [],
    ),
  'getAvailableStylistsForSlot' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Vec(Stylist)],
      [],
    ),
  'getAvailableTimeSlots' : IDL.Func([IDL.Text], [IDL.Vec(IDL.Text)], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getClosedDays' : IDL.Func([], [IDL.Vec(IDL.Text)], []),
  'getDailySchedules' : IDL.Func([], [IDL.Vec(DailySchedule)], ['query']),
  'getLunchBreaksForDate' : IDL.Func([IDL.Text], [IDL.Vec(Stylist)], []),
  'getProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getRefundRequests' : IDL.Func([], [IDL.Vec(RefundRequest)], ['query']),
  'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
  'getStylistAvailability' : IDL.Func([IDL.Text], [IDL.Vec(Stylist)], []),
  'getStylists' : IDL.Func([], [IDL.Vec(Stylist)], ['query']),
  'getTTSAudio' : IDL.Func([], [IDL.Vec(TTSAudio)], ['query']),
  'getTTSAudioById' : IDL.Func([IDL.Text], [IDL.Opt(TTSAudio)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getVoiceProfile' : IDL.Func([IDL.Text], [IDL.Opt(VoiceProfile)], ['query']),
  'getVoiceProfiles' : IDL.Func([], [IDL.Vec(VoiceProfile)], ['query']),
  'initializeAccessControl' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'processRefund' : IDL.Func([IDL.Text, IDL.Bool], [], []),
  'requestRefund' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveTTSAudio' : IDL.Func(
      [IDL.Text, IDL.Opt(IDL.Text), ExternalBlob, EffectSettings],
      [IDL.Text],
      [],
    ),
  'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateAppointment' : IDL.Func([Appointment], [], []),
  'updateDailySchedule' : IDL.Func([DailySchedule], [], []),
  'updateDailyStylistCount' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'updateProduct' : IDL.Func([Product], [], []),
  'updateStylist' : IDL.Func([Stylist], [], []),
  'updateStylistLunchBreak' : IDL.Func(
      [IDL.Text, IDL.Bool, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
      [],
      [],
    ),
  'updateTrainingStatus' : IDL.Func([IDL.Text, TrainingStatus], [], []),
  'updateVoiceProfile' : IDL.Func([IDL.Text, IDL.Vec(IDL.Text)], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const DailySchedule = IDL.Record({
    'lunchBreaks' : IDL.Vec(IDL.Text),
    'date' : IDL.Text,
    'isOpen' : IDL.Bool,
    'availableStylists' : IDL.Nat,
  });
  const Product = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'currency' : IDL.Text,
    'priceInCents' : IDL.Nat,
  });
  const Stylist = IDL.Record({
    'id' : IDL.Text,
    'lunchBreakStart' : IDL.Opt(IDL.Text),
    'name' : IDL.Text,
    'isAvailable' : IDL.Bool,
    'lunchBreakEnd' : IDL.Opt(IDL.Text),
    'isOnLunchBreak' : IDL.Bool,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const AppointmentStatus = IDL.Variant({
    'cancelled' : IDL.Null,
    'completed' : IDL.Null,
    'booked' : IDL.Null,
    'confirmed' : IDL.Null,
  });
  const PaymentStatus = IDL.Variant({
    'pending' : IDL.Null,
    'paid' : IDL.Null,
    'refunded' : IDL.Null,
    'notRequired' : IDL.Null,
  });
  const Appointment = IDL.Record({
    'id' : IDL.Text,
    'status' : AppointmentStatus,
    'depositAmount' : IDL.Nat,
    'assignedStylist' : IDL.Opt(IDL.Text),
    'paymentStatus' : PaymentStatus,
    'stylistRequest' : IDL.Opt(IDL.Text),
    'date' : IDL.Text,
    'createdAt' : IDL.Int,
    'parentPhone' : IDL.Text,
    'updatedAt' : IDL.Int,
    'childFirstName' : IDL.Text,
    'childLastName' : IDL.Text,
    'refundEligible' : IDL.Bool,
    'timeSlot' : IDL.Text,
  });
  const ShoppingItem = IDL.Record({
    'productName' : IDL.Text,
    'currency' : IDL.Text,
    'quantity' : IDL.Nat,
    'priceInCents' : IDL.Nat,
    'productDescription' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'phone' : IDL.Text,
  });
  const RefundStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
    'processed' : IDL.Null,
  });
  const RefundRequest = IDL.Record({
    'status' : RefundStatus,
    'processedAt' : IDL.Opt(IDL.Int),
    'amount' : IDL.Nat,
    'appointmentId' : IDL.Text,
    'requestedAt' : IDL.Int,
  });
  const StripeSessionStatus = IDL.Variant({
    'completed' : IDL.Record({
      'userPrincipal' : IDL.Opt(IDL.Text),
      'response' : IDL.Text,
    }),
    'failed' : IDL.Record({ 'error' : IDL.Text }),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const VoiceEffectPreset = IDL.Variant({
    'reverb' : IDL.Null,
    'alien' : IDL.Null,
    'deep' : IDL.Null,
    'echo' : IDL.Null,
    'robotic' : IDL.Null,
    'chipmunk' : IDL.Null,
  });
  const EffectSettings = IDL.Record({
    'tone' : IDL.Float64,
    'speed' : IDL.Float64,
    'preset' : IDL.Opt(VoiceEffectPreset),
    'pitch' : IDL.Float64,
  });
  const TTSAudio = IDL.Record({
    'id' : IDL.Text,
    'createdAt' : IDL.Int,
    'text' : IDL.Text,
    'audioBlob' : ExternalBlob,
    'voiceProfileId' : IDL.Opt(IDL.Text),
    'effectSettings' : EffectSettings,
  });
  const TrainingStatus = IDL.Variant({
    'notStarted' : IDL.Null,
    'completed' : IDL.Null,
    'inProgress' : IDL.Null,
    'failed' : IDL.Null,
  });
  const VoiceProfile = IDL.Record({
    'id' : IDL.Text,
    'userId' : IDL.Principal,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'audioBlob' : IDL.Opt(ExternalBlob),
    'updatedAt' : IDL.Int,
    'trainingStatus' : TrainingStatus,
    'referencePhrases' : IDL.Vec(IDL.Text),
  });
  const StripeConfiguration = IDL.Record({
    'allowedCountries' : IDL.Vec(IDL.Text),
    'secretKey' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'addDailySchedule' : IDL.Func([DailySchedule], [], []),
    'addProduct' : IDL.Func([Product], [], []),
    'addStylist' : IDL.Func([Stylist], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'cancelAppointment' : IDL.Func([IDL.Text], [], []),
    'createAppointment' : IDL.Func([Appointment], [], []),
    'createCheckoutSession' : IDL.Func(
        [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'createVoiceProfile' : IDL.Func(
        [IDL.Text, IDL.Vec(IDL.Text)],
        [IDL.Text],
        [],
      ),
    'deleteDailySchedule' : IDL.Func([IDL.Text], [], []),
    'deleteProduct' : IDL.Func([IDL.Text], [], []),
    'deleteStylist' : IDL.Func([IDL.Text], [], []),
    'deleteTTSAudio' : IDL.Func([IDL.Text], [], []),
    'deleteVoiceProfile' : IDL.Func([IDL.Text], [], []),
    'getAppointment' : IDL.Func([IDL.Text], [IDL.Opt(Appointment)], ['query']),
    'getAppointments' : IDL.Func([], [IDL.Vec(Appointment)], ['query']),
    'getAppointmentsByDate' : IDL.Func([IDL.Text], [IDL.Vec(Appointment)], []),
    'getAppointmentsByDateAndTimeSlot' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Vec(Appointment)],
        [],
      ),
    'getAppointmentsByDateRange' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Vec(Appointment)],
        [],
      ),
    'getAppointmentsByDateRangeAndStatus' : IDL.Func(
        [IDL.Text, IDL.Text, AppointmentStatus],
        [IDL.Vec(Appointment)],
        [],
      ),
    'getAppointmentsByDateRangeAndTimeSlot' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Vec(Appointment)],
        [],
      ),
    'getAppointmentsByPhone' : IDL.Func([IDL.Text], [IDL.Vec(Appointment)], []),
    'getAppointmentsByPhoneAndDateRange' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Vec(Appointment)],
        [],
      ),
    'getAppointmentsByStatus' : IDL.Func(
        [AppointmentStatus],
        [IDL.Vec(Appointment)],
        [],
      ),
    'getAppointmentsByStatusAndDate' : IDL.Func(
        [AppointmentStatus, IDL.Text],
        [IDL.Vec(Appointment)],
        [],
      ),
    'getAppointmentsByStatusAndDateRange' : IDL.Func(
        [AppointmentStatus, IDL.Text, IDL.Text],
        [IDL.Vec(Appointment)],
        [],
      ),
    'getAppointmentsByStatusAndTimeSlot' : IDL.Func(
        [AppointmentStatus, IDL.Text],
        [IDL.Vec(Appointment)],
        [],
      ),
    'getAppointmentsByStatusAndTimeSlotAndDateRange' : IDL.Func(
        [AppointmentStatus, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Vec(Appointment)],
        [],
      ),
    'getAppointmentsByStylist' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Appointment)],
        [],
      ),
    'getAppointmentsByStylistAndDateRange' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Vec(Appointment)],
        [],
      ),
    'getAppointmentsByTimeSlot' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Appointment)],
        [],
      ),
    'getAvailableDays' : IDL.Func([], [IDL.Vec(IDL.Text)], []),
    'getAvailableSlotsForDay' : IDL.Func([IDL.Text], [IDL.Vec(IDL.Text)], []),
    'getAvailableSlotsForStylist' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Vec(IDL.Text)],
        [],
      ),
    'getAvailableStylistsForSlot' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Vec(Stylist)],
        [],
      ),
    'getAvailableTimeSlots' : IDL.Func([IDL.Text], [IDL.Vec(IDL.Text)], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getClosedDays' : IDL.Func([], [IDL.Vec(IDL.Text)], []),
    'getDailySchedules' : IDL.Func([], [IDL.Vec(DailySchedule)], ['query']),
    'getLunchBreaksForDate' : IDL.Func([IDL.Text], [IDL.Vec(Stylist)], []),
    'getProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getRefundRequests' : IDL.Func([], [IDL.Vec(RefundRequest)], ['query']),
    'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
    'getStylistAvailability' : IDL.Func([IDL.Text], [IDL.Vec(Stylist)], []),
    'getStylists' : IDL.Func([], [IDL.Vec(Stylist)], ['query']),
    'getTTSAudio' : IDL.Func([], [IDL.Vec(TTSAudio)], ['query']),
    'getTTSAudioById' : IDL.Func([IDL.Text], [IDL.Opt(TTSAudio)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getVoiceProfile' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(VoiceProfile)],
        ['query'],
      ),
    'getVoiceProfiles' : IDL.Func([], [IDL.Vec(VoiceProfile)], ['query']),
    'initializeAccessControl' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'processRefund' : IDL.Func([IDL.Text, IDL.Bool], [], []),
    'requestRefund' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveTTSAudio' : IDL.Func(
        [IDL.Text, IDL.Opt(IDL.Text), ExternalBlob, EffectSettings],
        [IDL.Text],
        [],
      ),
    'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateAppointment' : IDL.Func([Appointment], [], []),
    'updateDailySchedule' : IDL.Func([DailySchedule], [], []),
    'updateDailyStylistCount' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'updateProduct' : IDL.Func([Product], [], []),
    'updateStylist' : IDL.Func([Stylist], [], []),
    'updateStylistLunchBreak' : IDL.Func(
        [IDL.Text, IDL.Bool, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
        [],
        [],
      ),
    'updateTrainingStatus' : IDL.Func([IDL.Text, TrainingStatus], [], []),
    'updateVoiceProfile' : IDL.Func([IDL.Text, IDL.Vec(IDL.Text)], [], []),
  });
};

export const init = ({ IDL }) => { return []; };