/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @dfinity/caffeine-bindgen@0.1.0-beta.7.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Appointment {
  'id' : string,
  'status' : AppointmentStatus,
  'depositAmount' : bigint,
  'assignedStylist' : [] | [string],
  'paymentStatus' : PaymentStatus,
  'stylistRequest' : [] | [string],
  'date' : string,
  'createdAt' : bigint,
  'parentPhone' : string,
  'updatedAt' : bigint,
  'childFirstName' : string,
  'childLastName' : string,
  'refundEligible' : boolean,
  'timeSlot' : string,
}
export type AppointmentStatus = { 'cancelled' : null } |
  { 'completed' : null } |
  { 'booked' : null } |
  { 'confirmed' : null };
export interface DailySchedule {
  'lunchBreaks' : Array<string>,
  'date' : string,
  'isOpen' : boolean,
  'availableStylists' : bigint,
}
export interface EffectSettings {
  'tone' : number,
  'speed' : number,
  'preset' : [] | [VoiceEffectPreset],
  'pitch' : number,
}
export type ExternalBlob = Uint8Array;
export type PaymentStatus = { 'pending' : null } |
  { 'paid' : null } |
  { 'refunded' : null } |
  { 'notRequired' : null };
export interface Product {
  'id' : string,
  'name' : string,
  'description' : string,
  'currency' : string,
  'priceInCents' : bigint,
}
export interface RefundRequest {
  'status' : RefundStatus,
  'processedAt' : [] | [bigint],
  'amount' : bigint,
  'appointmentId' : string,
  'requestedAt' : bigint,
}
export type RefundStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null } |
  { 'processed' : null };
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export interface Stylist {
  'id' : string,
  'lunchBreakStart' : [] | [string],
  'name' : string,
  'isAvailable' : boolean,
  'lunchBreakEnd' : [] | [string],
  'isOnLunchBreak' : boolean,
}
export interface TTSAudio {
  'id' : string,
  'createdAt' : bigint,
  'text' : string,
  'audioBlob' : ExternalBlob,
  'voiceProfileId' : [] | [string],
  'effectSettings' : EffectSettings,
}
export type TrainingStatus = { 'notStarted' : null } |
  { 'completed' : null } |
  { 'inProgress' : null } |
  { 'failed' : null };
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserProfile {
  'name' : string,
  'email' : string,
  'phone' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type VoiceEffectPreset = { 'reverb' : null } |
  { 'alien' : null } |
  { 'deep' : null } |
  { 'echo' : null } |
  { 'robotic' : null } |
  { 'chipmunk' : null };
export interface VoiceProfile {
  'id' : string,
  'userId' : Principal,
  'name' : string,
  'createdAt' : bigint,
  'audioBlob' : [] | [ExternalBlob],
  'updatedAt' : bigint,
  'trainingStatus' : TrainingStatus,
  'referencePhrases' : Array<string>,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'addDailySchedule' : ActorMethod<[DailySchedule], undefined>,
  'addProduct' : ActorMethod<[Product], undefined>,
  'addStylist' : ActorMethod<[Stylist], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'cancelAppointment' : ActorMethod<[string], undefined>,
  'createAppointment' : ActorMethod<[Appointment], undefined>,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'createVoiceProfile' : ActorMethod<[string, Array<string>], string>,
  'deleteDailySchedule' : ActorMethod<[string], undefined>,
  'deleteProduct' : ActorMethod<[string], undefined>,
  'deleteStylist' : ActorMethod<[string], undefined>,
  'deleteTTSAudio' : ActorMethod<[string], undefined>,
  'deleteVoiceProfile' : ActorMethod<[string], undefined>,
  'getAppointment' : ActorMethod<[string], [] | [Appointment]>,
  'getAppointments' : ActorMethod<[], Array<Appointment>>,
  'getAppointmentsByDate' : ActorMethod<[string], Array<Appointment>>,
  'getAppointmentsByDateAndTimeSlot' : ActorMethod<
    [string, string],
    Array<Appointment>
  >,
  'getAppointmentsByDateRange' : ActorMethod<
    [string, string],
    Array<Appointment>
  >,
  'getAppointmentsByDateRangeAndStatus' : ActorMethod<
    [string, string, AppointmentStatus],
    Array<Appointment>
  >,
  'getAppointmentsByDateRangeAndTimeSlot' : ActorMethod<
    [string, string, string],
    Array<Appointment>
  >,
  'getAppointmentsByPhone' : ActorMethod<[string], Array<Appointment>>,
  'getAppointmentsByPhoneAndDateRange' : ActorMethod<
    [string, string, string],
    Array<Appointment>
  >,
  'getAppointmentsByStatus' : ActorMethod<
    [AppointmentStatus],
    Array<Appointment>
  >,
  'getAppointmentsByStatusAndDate' : ActorMethod<
    [AppointmentStatus, string],
    Array<Appointment>
  >,
  'getAppointmentsByStatusAndDateRange' : ActorMethod<
    [AppointmentStatus, string, string],
    Array<Appointment>
  >,
  'getAppointmentsByStatusAndTimeSlot' : ActorMethod<
    [AppointmentStatus, string],
    Array<Appointment>
  >,
  'getAppointmentsByStatusAndTimeSlotAndDateRange' : ActorMethod<
    [AppointmentStatus, string, string, string],
    Array<Appointment>
  >,
  'getAppointmentsByStylist' : ActorMethod<[string], Array<Appointment>>,
  'getAppointmentsByStylistAndDateRange' : ActorMethod<
    [string, string, string],
    Array<Appointment>
  >,
  'getAppointmentsByTimeSlot' : ActorMethod<[string], Array<Appointment>>,
  'getAvailableDays' : ActorMethod<[], Array<string>>,
  'getAvailableSlotsForDay' : ActorMethod<[string], Array<string>>,
  'getAvailableSlotsForStylist' : ActorMethod<[string, string], Array<string>>,
  'getAvailableStylistsForSlot' : ActorMethod<[string, string], Array<Stylist>>,
  'getAvailableTimeSlots' : ActorMethod<[string], Array<string>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getClosedDays' : ActorMethod<[], Array<string>>,
  'getDailySchedules' : ActorMethod<[], Array<DailySchedule>>,
  'getLunchBreaksForDate' : ActorMethod<[string], Array<Stylist>>,
  'getProducts' : ActorMethod<[], Array<Product>>,
  'getRefundRequests' : ActorMethod<[], Array<RefundRequest>>,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'getStylistAvailability' : ActorMethod<[string], Array<Stylist>>,
  'getStylists' : ActorMethod<[], Array<Stylist>>,
  'getTTSAudio' : ActorMethod<[], Array<TTSAudio>>,
  'getTTSAudioById' : ActorMethod<[string], [] | [TTSAudio]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getVoiceProfile' : ActorMethod<[string], [] | [VoiceProfile]>,
  'getVoiceProfiles' : ActorMethod<[], Array<VoiceProfile>>,
  'initializeAccessControl' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'processRefund' : ActorMethod<[string, boolean], undefined>,
  'requestRefund' : ActorMethod<[string, bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveTTSAudio' : ActorMethod<
    [string, [] | [string], ExternalBlob, EffectSettings],
    string
  >,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateAppointment' : ActorMethod<[Appointment], undefined>,
  'updateDailySchedule' : ActorMethod<[DailySchedule], undefined>,
  'updateDailyStylistCount' : ActorMethod<[string, bigint], undefined>,
  'updateProduct' : ActorMethod<[Product], undefined>,
  'updateStylist' : ActorMethod<[Stylist], undefined>,
  'updateStylistLunchBreak' : ActorMethod<
    [string, boolean, [] | [string], [] | [string]],
    undefined
  >,
  'updateTrainingStatus' : ActorMethod<[string, TrainingStatus], undefined>,
  'updateVoiceProfile' : ActorMethod<[string, Array<string>], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];